import numpy as np
array1 = np.array([[2,4,5,4], [3,5,6,5]])
array2 = np.array([[3,4,5,5], [4,5,6,5]])
print("array1 is:\n",array1.ndim)
print("array2 is:\n",array2.ndim)
adding_arrays = array1+array2
print("adding arrays is :\n",adding_arrays)
matrix = np.dot(array1,array2.T)
print("the matrix arrays is:\n",matrix)

matrix1 = np.array([[[1, 2], [3, 4]]])
matrix2 = np.array([[[5, 6], [7, 8]]])

multiplay_arrays = matrix1*matrix2
print("the multiplication array is:\n",multiplay_arrays)
print("the size of the multiplication array is:\n",multiplay_arrays.size)
print("the shape of the multiplication array is:\n",multiplay_arrays.shape)
print("the ndim of the multiplication array is:\n",multiplay_arrays.ndim)
transpose = np.array([[2,3,4,5],[4,5,6,7],[5,6,7,8],[6,7,7,8],[7,8,9,0],[3,4,5,8],[5,6,7,7],[4,5,6,7],[6,8,9,7],[7,5,8,9],[6,7,8,4],[3,5,7,8]])
print("the tranpspose ayyay is:\n",transpose.transpose())
print("shape of the transpose array is:\n",transpose.shape)
print("the size of the transpose array is:\n",transpose.size)
print("the dimension of the transpose array is:\n",transpose.ndim)
print("the reversed array of the transopose is:\n",transpose[::-1])
reshape = transpose.reshape(6,2,4)
print("reshape the transpose array is:\n",reshape)
print("shape of the reshaped array is:\n",reshape.shape)
print("dimensions of the reshaped array is:\n",reshape.ndim)
print("sum of the reshaped array is ;\n",transpose.sum())
concadination = np.concatenate((array1,array2), axis=0)
print("array1 is :\n",array1)
print("array2 is:\n",array2)
print("concadination of array1 and array2 is:\n",concadination)
cancadination2  = np.concatenate((array1,array2),axis=1)
print("concadination2 of array1 and array2 is :\n",cancadination2)